server:
  port: 16200
  
spring:
  profiles: dev

eureka:
  instance:
    hostname: discovery
    perferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
person:
  name: guotao
  age: 25
      
---
server:
  port: 16200
  
spring:
  profiles: test

eureka:
  instance:
    hostname: discovery
    perferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
person:
  name: luotong
  age: 25
