server:
  port: 6702
  
spring:
  profiles: dev
  cloud:
    config:
      discovery:
        enabled: true
eureka:
  instance:
    hostname: discovery
#    perferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
person:
  name: langlang
  age: 25
      
---
server:
  port: 6702
  
spring:
  profiles: test

eureka:
  instance:
    hostname: discovery
    perferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
person:
  name: luotong
  age: 25
