server:
  port: 6705
  
spring:
  profiles: dev
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
  
ribbon:
  eureka:
    enabled: true
  
---
server:
  port: 6705
  
spring:
  profiles: test
