server:
  port: 6705
  
spring:
  profiles: dev
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

# 服务注册配置
eureka:
  instance:
    hostname: feign-consumer
    perferIpAddress: true
     # 心跳频率设置为15s，默认30s
    lease-renewal-interval-in-seconds: 15
    # 服务过期剔除时间设置为45s，默认90s，两次心跳时间间隔45s，服务就会剔除（即：服务状态为DOWN，Eureka Server将其剔除）
    lease-expiration-duration-in-seconds: 45
  client:
    serviceUrl:
      defaultZone: http://discovery:6702/eureka/
    healthcheck:
      enable: true
      # 配置Eureka客户端拉取服务注册列表信息时间为10s，默认60，可以快速获取服务列表
    registry-fetch-interval-seconds: 10 

# 服务消费-客户端负载均衡配置，ribbon和erureka结合使用，从服务注册中心查找可调用服务
ribbon:
  eureka:
    enabled: true
  
---
server:
  port: 6705
  
spring:
  profiles: test
