server:
  port: 6700
  
spring:
  profiles: dev

# 服务注册配置
eureka:
  instance:
    hostname: gateway
    perferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:6702/eureka/

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    users:
      path: /user-api/**
      serviceId: user-service
  
---
server:
  port: 6700
  
spring:
  profiles: test
