server:
  port: 6700
  
spring:
  profiles: dev

# 服务注册配置
eureka:
  instance:
    hostname: gateway
    perferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:6702/eureka/

zuul:
  # 路由超时配置
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    users:
      path: /user-api/**
      serviceId: user-service

# 断路器超时配置
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
  
---
server:
  port: 6700
  
spring:
  profiles: test
