server:
  port: 6704
  
spring:
  profiles: dev

# 服务实例注册配置
eureka:
  instance:
    hostname: service-A
    perferIpAddress: true
    # instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${random.int}
    # 心跳频率设置为15s，默认30s
    lease-renewal-interval-in-seconds: 15
    # 服务过期剔除时间设置为45s，默认90s，两次心跳时间间隔45s，服务就会剔除（即：服务状态为DOWN，Eureka Server将其剔除）
    lease-expiration-duration-in-seconds: 45
  client:
    serviceUrl:
      defaultZone: http://discovery:6702/eureka/
    healthcheck:
      enable: true
  
 
# ribbon和eureka结合使用，客户端负载均衡，从服务中心获取服务列表
ribbon:
  eureka:
    enabled: true
