server:
  port: 6703
  
spring:
  profiles: dev
  cloud:
    config:
      discovery:
        enabled: true
  
eureka:
  instance:
    hostname: user-service
    perferIpAddress: true
#    lease-expiration-duration-in-seconds: 30 
 #   lease-renewal-interval-in-seconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:6702/eureka/
  #  healthcheck:
   #   enabled: true
      
---
server:
  port: 6703
  
spring:
  profiles: dev
  cloud:
    config:
      discovery:
        enabled: true
  
eureka:
  instance:
    hostname: user-service
    perferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:6702/eureka/
