server:
  port: 0
  
spring:
  profiles: dev
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

# 服务实例注册配置
eureka:
  instance:
    hostname: user-service
    perferIpAddress: true 
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: http://discovery:6702/eureka/
    healthcheck:
      enable: true
      
user:
  name: pingping
---
server:
  port: 6703
  
spring:
  profiles: test
