server:
  port: 0
  
spring:
  profiles: dev
  
 endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
  
user:
  name: pingping
---
server:
  port: 6703
  
spring:
  profiles: test
