server:
  port: 6703
  
spring:
  profiles: dev
  
  rabbitmq:
    host: 127.0.0.1
    port: 15672
    username: guest
    password: guest
  
user:
  name: gege
---
server:
  port: 6703
  
spring:
  profiles: test
